bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("account/", include("account.urls")),
        path("social-auth/", include("social_django.urls", namespace="social")),
        path("images/", include("images.urls", namespace="images")),
        path("__reload__/", include("django_browser_reload.urls")),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

images/urls.py
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path("create/", views.image_create, name="create"),
    path("detail/<int:id>/<slug:slug>/", views.image_detail, name="detail"),
    path("like/", views.image_like, name="like"),
    path("", views.image_list, name="list"),
    path("ranking/", views.image_ranking, name="ranking"),
]

images/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="images_created",
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)  # Original URL
    image = models.ImageField(upload_to="images/%Y/%m/%d/")
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="images_liked", blank=True
    )
    # Denormalizes `users_like` counts.
    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=["-created"]),
            models.Index(fields=["-total_likes"]),
        ]
        ordering = ["-created"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])

images/forms.py
import requests
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["title", "url", "description"]
        widgets = {
            # We'll use a JavaScript tool to choose an image from an
            #   external site, and receive the image's URL as a parameter.
            "url": forms.HiddenInput,
        }

    def clean_url(self):
        url: str = self.cleaned_data["url"]
        url = url.split("?")[0]  # To discard any querystring.
        valid_extensions = ["jpg", "jpeg", "png"]
        extension = url.rsplit(".", 1)[1].lower()  # Splitting starts at the end.
        if extension not in valid_extensions:
            raise forms.ValidationError(
                f"The given URL does not match valid image extensions. {extension}"
            )
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image: Image = super().save(commit=False)
        image_url: str = image.url
        name = slugify(image.title)
        extension = image_url.rsplit(".", 1)[1].lower()
        image_name = f"{name}.{extension}"

        # Download image from the given URL.
        response = requests.get(image_url)
        # `save=False` prevents the object (`image`) from being saved to the db.
        image.image.save(image_name, ContentFile(response.content), save=False)

        # To maintain the same behavior as the original `save()`.
        if commit:
            image.save()
        return image

images/views.py
import redis
from actions.utils import create_action
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, JsonResponse
from django.http.request import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from bookmarks.typing import settings

from .forms import ImageCreateForm
from .models import Image

# Connect to redis
r = redis.Redis(
    host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB
)


@login_required
def image_create(request: HttpRequest):
    if request.method == "POST":
        # Form is sent.
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            # Assign current user to the object.
            new_image.user = request.user
            new_image.save()
            create_action(request.user, "bookmarked image", new_image)
            messages.success(request, "Image added successfully")
            # Redirect to new created item detail view.
            return redirect(new_image.get_absolute_url())
    else:
        # Build form with data provided by the bookmarklet via GET.
        form = ImageCreateForm(data=request.GET)

    return render(
        request, "images/image/create.html", {"section": "images", "form": form}
    )


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # Increment total image views by 1.
    total_views = r.incr(f"image:{image.id}:views")
    # Increment image ranking by 1.
    r.zincrby("image_ranking", 1, image.id)
    return render(
        request,
        "images/image/detail.html",
        {"section": "images", "image": image, "total_views": total_views},
    )


@login_required
@require_POST
def image_like(request: HttpRequest):
    image_id = request.POST.get("id")
    action = request.POST.get("action")
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == "like":
                image.users_like.add(request.user)
                create_action(request.user, "likes", image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({"status": "ok"})
        except Image.DoesNotExist:
            pass
    return JsonResponse({"status": "error"})


@login_required
def image_list(request: HttpRequest):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get("page")
    images_only = request.GET.get("images_only")  # Flag to distinguish AJAX.

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page.
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # If AJAX request and page out of range return an empty page.
            return HttpResponse("")
        # If page out of range return last page of results.
        images = paginator.page(paginator.num_pages)

    if images_only:
        return render(
            request,
            "images/image/list_images.html",
            {"section": "images", "images": images},
        )

    return render(
        request,
        "images/image/list.html",
        {"section": "images", "images": images},
    )


@login_required
def image_ranking(request):
    # * Get image ranking dictionary.
    # `start=0` specifies the lowest score. `end=-1` specifies the highest score.
    #   Range of 0 to -1 returns all elements.
    image_ranking_list: list[tuple[bytes, int]] = r.zrange(
        "image_ranking",
        start=0,
        end=-1,
        desc=True,
        withscores=True,
        score_cast_func=int,
    )[:10]
    image_ranking = {int(key): value for key, value in image_ranking_list}
    image_ranking_ids = list(image_ranking)
    # * Get most viewed images.
    # Force query to be executed using `list()`.
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    # Sort by index of appearance in the image ranking.
    most_viewed.sort(key=lambda image: image_ranking_ids.index(image.id))
    for image in most_viewed:
        image.views = image_ranking.get(image.id)

    return render(
        request,
        "images/image/ranking.html",
        {"section": "images", "most_viewed": most_viewed},
    )

images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}
  Bookmark an image
{% endblock title %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!">
  </form>
{% endblock content %}

images/templates/images/image/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  {{ image.title }}
{% endblock title %}

{% block content %}
  <h1>{{ image.title }}</h1>
  {% load thumbnail %}
  <a href="{{ image.image.url }}" target="_blank">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
  </a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <span class="count">{{ total_views }} view{{ total_views|pluralize }}</span>
        {% comment %} Use data-* attributes to store request params. {% endcomment %}
        <a href="#"
           data-id="{{ image.id }}"
           data-action="{% if request.user in users_like %}un{% endif %}like"
           class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in users_like %}
        <div>
          {% if user.profile.photo %}<img src="{{ user.profile.photo.url }}">{% endif %}
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock content %}

{% block script %}
  <div class="template-data" data-url="{% url "images:like" %}"></div>
  <script type="module" src="{% static "js/image-detail.js" %}"></script>
{% endblock script %}

images/templates/images/image/list.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Images bookmarked
{% endblock title %}

{% block content %}
  <h1>Images bookmarked</h1>
  <div id="image-list">{% include "images/image/list_images.html" %}</div>
{% endblock content %}

{% block script %}
  <script type="module" src="{% static "js/image-list.js" %}"></script>
{% endblock script %}

images/templates/images/image/list_images.html
{% load thumbnail %}

{% for image in images %}
  <div class="image">
    <a href="{{ image.get_absolute_url }}">
      <a href="{{ image.get_absolute_url }}">
        <img src="{% thumbnail image.image 300x300 crop="smart" %}">
      </a>
    </a>
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
    </div>
  </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends "base.html" %}

{% block title %}
  Images ranking
{% endblock title %}

{% block content %}
  <h1>Images ranking</h1>
  <ol>
    {% for image in most_viewed %}
      <li>
        <a href="{{ image.get_absolute_url }}">{{ image.title }} · {{ image.views }}</a>
      </li>
    {% endfor %}
  </ol>
{% endblock content %}